apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-training-internal
  namespace: training-app
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/part-of: training-workload
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: training-workload
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: training-workload
    - to:
        - namespaceSelector: {}
